---

- name: Common
  hosts: common
  user: deploy
  become: yes
  roles:
    - common
  tags: ['common']

- name: AzerothCore
  hosts: acore
  user: "{{ inventory_hostname }}"
  roles: ['azerothcore']
  tags: ['acore']

- name: Winzig
  hosts: winzig
  user: winzig
  roles: ['winzig']
  tags: ['winzig']