---

- name: Common configuration
  hosts: mikxi
  user: deploy
  become: yes
  gather_facts: yes
  roles:
    - common
  tags: ['common']

- name: Database configuration
  hosts: mikxi
  vars:
    mysql_pass: "{{ lookup('env', 'MYSQL_PASS') }}"
  user: deploy
  become: yes
  gather_facts: yes
  roles:
    - database
  tags: ['database']

- name: AzerothCore configuration
  hosts: mikxi
  vars:
    mysql_pass: "{{ lookup('env', 'MYSQL_PASS') }}"
  user: "{{ inventory_hostname }}"
  gather_facts: yes
  roles:
    - azerothcore
  tags: ['azerothcore']

- name: Winzig configuration
  hosts: winzig
  user: winzig
  gather_facts: yes
  roles:
    - winzig
  tags: ['winzig']