---

- name: Common configuration
  hosts: all
  user: deploy
  become: yes
  roles: ['common']
  tags: ['common']

- name: Backup configuration
  hosts: backup
  user: deploy
  become: yes
  roles: ['backup']
  tags: ['backup']

- name: Backup repository
  hosts: backup
  user: bup
  tasks:
    - name: Check if backup repository is already initialised
      shell: restic -r repo snapshots
      args:
        chdir: /home/bup
      environment:
        RESTIC_PASSWORD: "{{ backup.pass }}"
      register: restic
      failed_when: restic.rc not in [0, 1]

    - name: Initialise backup repository
      command: restic -r repo init
      args:
        chdir: /home/bup
      environment:
        RESTIC_PASSWORD: "{{ backup.pass }}"
      when: 'restic.rc == 1'
  tags: ['backup']

- name: Application configuration
  hosts: app
  user: deploy
  become: yes
  roles: ['app']
  tags: ['app']

- name: Authorise backups
  hosts: backup
  user: deploy
  become: yes
  tasks:
    - name: Authorise public keys on backup servers
      authorized_key:
        user: bup
        key: "{{ hostvars[item]['pubkey'] }}"
      with_items: "{{ groups['common'] | select('in', ansible_limit) }}"
  tags: ['common']

- name: Proxy configuration
  hosts: proxy
  user: deploy
  become: yes
  roles: ['proxy']
  tags: ['proxy']

- name: AzerothCore configuration
  hosts: acore
  user: "{{ inventory_hostname }}"
  roles: ['azerothcore']
  tags: ['acore']

- name: Winzig configuration
  hosts: winzig
  user: winzig
  roles: ['winzig']
  tags: ['winzig']

- name: MinIO configuration
  hosts: web
  user: deploy
  become: yes
  roles: ['minio']
  tags: ['minio']

- name: Start minio
  hosts: web
  user: web
  tasks:
    - name: Start minio
      command: "/bin/bash /home/minio/startup.sh"
  tags: ['start-minio']

- name: Kill minio
  hosts: web
  user: web
  tasks:
    - name: Kill minio
      command: tmux kill-server
  tags: ['kill-minio']