---

- name: Set firewall rules
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - http
    - https

- name: Install dependencies
  apt:
    name:
      - nginx
      - snapd
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Clone website
  git:
    repo: "{{ proxy.website }}"
    dest: /var/www/wobgob.com
    version: "{{ proxy.version }}"

- name: Copy HTTP configuration
  template:
    src: wobgob.com.http.j2
    dest: /etc/nginx/sites-available/wobgob.com

- name: Enable website
  file:
    src: /etc/nginx/sites-available/wobgob.com
    dest: /etc/nginx/sites-enabled/wobgob.com
    state: link

- name: Disable default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy load balancer configuration
  template:
    src: load-balancer.conf.j2
    dest: /etc/nginx/conf.d/load-balancer.conf

- name: Get certbot
  community.general.snap:
    name: certbot
    classic: yes
    state: present

- name: Link certbot
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Restart nginx
  systemd:
    state: restarted
    name: nginx

- name: Run certbot
  command: "certbot certonly -d {{ proxy.domains | join(',') }} --webroot -n --agree-tos -m {{ proxy.email }} -w /var/www/wobgob.com"

- name: Copy HTTPS configuration
  template:
    src: wobgob.com.https.j2
    dest: /etc/nginx/sites-available/wobgob.com

- name: Enable website
  file:
    src: /etc/nginx/sites-available/wobgob.com
    dest: /etc/nginx/sites-enabled/wobgob.com
    state: link

- name: Restart nginx
  systemd:
    state: restarted
    name: nginx

- name: Test automatic renewal
  command: certbot renew --dry-run

- name: Enable nginx
  systemd:
    enabled: yes
    name: nginx