---

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install python dependencies
  pip:
    name: pymysql

- name: Create database user
  mysql_user:
    name: acore
    password: "{{ mysql_pass }}"
    priv: '*.*:ALL,GRANT'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create databases
  mysql_db:
    name:
      - acore_world
      - acore_characters
      - acore_auth
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Grant all privileges to the databases
  mysql_user:
    name: acore
    password: "{{ mysql_pass }}"
    state: present
    priv:
      'acore_world.*': 'ALL,GRANT'
      'acore_characters.*': 'ALL,GRANT'
      'acore_auth.*': 'ALL,GRANT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Update the realmlist
  community.mysql.mysql_query:
    login_db: acore_auth
    query: UPDATE realmlist SET name = "{{ realmlist.name }}", address = "{{ ansible_default_ipv4.address }}" WHERE id = 1
    login_unix_socket: /var/run/mysqld/mysqld.sock