---

- name: Install pip
  apt:
    name: python3-pip
    state: present

- name: Install python dependencies
  pip:
    name: pymysql

- name: Create database user
  mysql_user:
    name: acore
    password: "{{ database.pass }}"
    priv: '*.*:ALL,GRANT'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create databases
  mysql_db:
    name:
      - "{{ realm.world_db }}"
      - "{{ realm.char_db }}"
      - acore_auth
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Grant all privileges to the databases
  mysql_user:
    name: acore
    password: "{{ database.pass }}"
    state: present
    priv:
      'acore_world.*': 'ALL,GRANT'
      'acore_characters.*': 'ALL,GRANT'
      'acore_auth.*': 'ALL,GRANT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add realm to realmlist
  community.mysql.mysql_query:
    login_user: acore
    login_password: "{{ database.pass }}"
    login_db: acore_auth
    query: "INSERT INTO realmlist (id, name, address, port) VALUES ({{ realm.id }}, '{{ realm.name }}', '{{ ansible_host }}', {{ realm.port }})"
    login_unix_socket: /var/run/mysqld/mysqld.sock