---

- name: Create backup user
  user:
    name: bup
    shell: /bin/bash
    state: present

- name: Set authorized key for backup user copying it from the current user
  authorized_key:
    user: bup
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Install restic
  apt:
    name:
      - restic
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Add weekly cron job to delete all snapshots older than 6 months
  cron:
    name: Weekly pruning
    weekday: 2
    hour: 0
    minute: 0
    job: /usr/bin/restic -r /home/bup/repo forget --keep-within 0y6m0d0h --prune