---

- name: Checkout AzerothCore source
  git:
    repo: "{{ acore.git }}"
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk"
    version: "{{ acore.version }}"

- name: Copy config.sh
  copy:
    src: "/home/{{ inventory_hostname }}/azerothcore-wotlk/conf/dist/config.sh"
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk/conf/config.sh"
    remote_src: yes
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Create log folder
  file:
    path: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/log"
    state: directory
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Copy scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ inventory_hostname }}/{{ item }}"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"
  with_items:
    - startup.sh
    - worldserver.sh

- name: Create configuration directory
  file:
    path: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/etc"
    state: directory
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Copy configuration
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/etc/{{ item }}"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"
  with_items:
    - worldserver.conf
    - authserver.conf

- name: Checkout AzerothCore modules
  git:
    repo: "{{ item.git }}"
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk/modules/{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ acore.modules }}"

- name: Copy module configuration
  copy:
    src: modules
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/etc/modules"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Create binary directory
  file:
    path: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/bin"
    state: directory
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Get client data
  get_url:
    url: "{{ acore.data }}"
    dest: "/home/{{ inventory_hostname }}/data.zip"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Extract client data
  unarchive:
    src: "/home/{{ inventory_hostname }}/data.zip"
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/bin"
    remote_src: yes