---

- name: Checkout AzerothCore source
  git:
    repo: "{{ acore.git }}"
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk"
    version: "{{ acore.version }}"

- name: Copy config.sh
  copy:
    src: "/home/{{ inventory_hostname }}/azerothcore-wotlk/conf/dist/config.sh"
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk/conf/config.sh"
    remote_src: yes
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Create log folder
  file:
    path: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/log"
    state: directory
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Copy scripts
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ inventory_hostname }}/{{ item }}"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"
  with_items:
    - startup.sh
    - worldserver.sh

- name: Create configuration directory
  file:
    path: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/etc"
    state: directory
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Copy configuration
  template:
    src: "{{ item }}.j2"
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/etc/{{ item }}"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"
  with_items:
    - worldserver.conf
    - authserver.conf

- name: Copy module configuration
  copy:
    src: modules
    dest: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/etc/modules"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Create binary directory
  file:
    path: "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/bin"
    state: directory
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Get client data
  get_url:
    url: "{{ acore.data }}"
    dest: "/home/{{ inventory_hostname }}/data.zip"
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Extract client data
  command: unzip -d "/home/{{ inventory_hostname }}/azerothcore-wotlk/env/dist/bin" -n "/home/{{ inventory_hostname }}/data.zip"

- name: Checkout acore-console source
  git:
    repo: "{{ acore.console.git }}"
    dest: "/home/{{ inventory_hostname }}/acore-console"
    version: "{{ acore.console.version }}"

- name: Copy acore-console config
  template:
    src: config.js.j2
    dest: "/home/{{ inventory_hostname }}/acore-console/config.js"
    mode: '0640'
    owner: "{{ inventory_hostname }}"
    group: "{{ inventory_hostname }}"

- name: Run acore-console at reset
  cron:
    name: "Daily Macaroons"
    minute: "0"
    hour: "0"
    job: "/usr/bin/node /home/{{ inventory_hostname }}/acore-console/index.js 'daily macaroons'"
