---

- name: Automatically install security updates
  debconf: name=unattended-upgrades question=unattended-upgrades/enable_auto_updates vtype=boolean value='true'

- name: Install unattended-upgrades
  apt: name=unattended-upgrades

- name: Enable unattended-upgrades
  command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    creates: /etc/apt/apt.conf.d/20auto-upgrades

- name: Install ufw
  apt: pkg=ufw state=present

- name: Deny everything
  ufw: policy=deny

- name: Set firewall rule for DNS
  ufw: rule=allow port=domain

- name: Set firewall rules for SSH
  ufw: rule=allow port=ssh proto=tcp

- name: Enable UFW
  ufw: state=enabled

- name: Copy tmux config
  copy:
    src: tmux.conf
    dest: /etc/tmux.conf
    owner: root
    group: root
    mode: '0644'