---

- name: Automatically install security updates
  debconf: name=unattended-upgrades question=unattended-upgrades/enable_auto_updates vtype=boolean value='true'

- name: Install unattended-upgrades
  apt: name=unattended-upgrades

- name: Enable unattended-upgrades
  command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    creates: /etc/apt/apt.conf.d/20auto-upgrades

- name: Install ufw
  apt: pkg=ufw state=present

- name: Deny everything
  ufw: policy=deny

- name: Set firewall rule for DNS
  ufw: rule=allow port=domain

- name: Set firewall rules for web traffic and SSH
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - http
    - https
    - ssh

- name: Set firewall rules for AzerothCore
  ufw: rule=allow port={{ item }}
  with_items:
    - 3306
    - 3724
    - 8085

- name: Enable UFW
  ufw: state=enabled

- name: Create user azerothcore
  user:
    name: azerothcore
    shell: /bin/bash
    system: yes
    state: present

- name: Set authorized key for user azerothcore copying it from the current user
  authorized_key:
    user: azerothcore
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Create user winzig
  user:
    name: winzig
    shell: /bin/bash
    system: yes
    state: present

- name: Set authorized key for user winzig copying it from the current user
  authorized_key:
    user: winzig
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Install AzerothCore dependencies
  apt:
    name:
      - git
      - cmake
      - make
      - gcc
      - g++
      - clang
      - libmysqlclient-dev
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - libncurses-dev
      - mysql-server
      - libace-6.*
      - libboost-all-dev
      - libace-dev
      - python3
      - python3-pip
      - zip
      - mysql-client
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Add Node.js to repositories
  shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: Install Node.js
  apt:
    name: nodejs
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install tmux
  apt:
    name: tmux
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Copy tmux config
  copy:
    src: tmux.conf
    dest: "/home/{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - azerothcore
    - winzig

- name: Install pyrogram and tgcrypto
  pip:
    name:
      - pyrogram
      - tgcrypto