---

- name: Automatically install security updates
  debconf: name=unattended-upgrades question=unattended-upgrades/enable_auto_updates vtype=boolean value='true'

- name: Install unattended-upgrades
  apt: name=unattended-upgrades

- name: Enable unattended-upgrades
  command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    creates: /etc/apt/apt.conf.d/20auto-upgrades

- name: Install ufw
  apt: pkg=ufw state=present

- name: Deny everything
  ufw: policy=deny

- name: Set firewall rule for DNS
  ufw: rule=allow port=domain
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Set firewall rules for web traffic and SSH
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - http
    - https
    - ssh

- name: Set firewall rules for AzerothCore
  ufw: rule=allow port={{ item }}
  with_items:
    - 3306
    - 3724
    - "{{ realmlist.port }}"

- name: Enable UFW
  ufw: state=enabled

- name: Create user for AzerothCore
  user:
    name: "{{ inventory_hostname }}"
    shell: /bin/bash
    system: yes
    state: present

- name: Set authorized key for user for AzerothCore copying it from the current user
  authorized_key:
    user: "{{ inventory_hostname }}"
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Create user winzig
  user:
    name: winzig
    shell: /bin/bash
    system: yes
    state: present

- name: Set authorized key for user winzig copying it from the current user
  authorized_key:
    user: winzig
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Install AzerothCore dependencies
  apt:
    name:
      - git
      - cmake
      - make
      - gcc
      - g++
      - clang
      - libmysqlclient-dev
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - libncurses-dev
      - mysql-server
      - libboost-all-dev
      - unzip
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Add Node.js to repositories
  shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: Install Node.js, Python, and tmux
  apt:
    name:
      - nodejs
      - python3
      - python3-pip
      - tmux
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install pyrogram, tgcrypto, and pymysql
  pip:
    name:
      - pyrogram
      - tgcrypto
      - pymysql

- name: Copy tmux config
  copy:
    src: tmux.conf
    dest: "/home/{{ item }}/.tmux.conf"
    owner: "{{ item }}"
    group: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - winzig

- name: Create databases
  mysql_db:
    name:
      - "{{ database.world }}"
      - "{{ database.characters }}"
      - "{{ database.auth }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create user
  mysql_user:
    name: "{{ mysql.user }}"
    password: "{{ mysql.pass }}"
    host: "{{ item }}"
    priv: '*.*:ALL,GRANT'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - localhost
    - 127.0.0.1