---

- name: Add Node.js to repositories
  shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: Install dependencies
  apt:
    name:
      - nodejs
      - mysql-server
    update_cache: yes
  become: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Checkout Winzig code
  git:
    repo: https://github.com/wobgob/winzig.git
    dest: /home/winzig/winzig
    version: main

- name: Copy startup.sh
  template:
    src: startup.sh.j2
    dest: /home/winzig/startup.sh
    owner: winzig
    group: winzig
    mode: '0600'