---

- name: Checkout Winzig code
  git:
    repo: https://github.com/wobgob/winzig.git
    dest: /home/winzig/winzig
    version: main

- name: Copy config.js
  template:
    src: config.js.j2
    dest: /home/winzig/winzig/config.js
    owner: winzig
    group: winzig
    mode: '0600'

- name: Copy startup.sh
  template:
    src: startup.sh.j2
    dest: /home/winzig/startup.sh
    owner: winzig
    group: winzig
    mode: '0600'